name = "IDDET Ads"
# Replace this value with the Client ID from the Shopify Dev Dashboard before
# running `shopify app dev` or deploying the app through Shopify CLI.
client_id = "4a1709ade5230f37f466887ad3f00166"
application_url = "https://iddet-ads-shopify--bkabuya19ben.replit.app/"
embedded = true

[build]
automatically_update_urls = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://iddet-ads-shopify--bkabuya19ben.replit.app/api/shopify/oauth/callback",
]

[webhooks]
api_version = "2025-10"